In [5]:
import pandas as pd
import numpy as np
import difflib # for wrong input
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
dataset = pd.read_csv('imdb_movies.csv')

In [7]:
# @title
dataset.head()

names       date_x  score  \
0                    Creed III  03/02/2023    73.0   
1     Avatar: The Way of Water  12/15/2022    78.0   
2  The Super Mario Bros. Movie  04/05/2023    76.0   
3                      Mummies  01/05/2023    70.0   
4                    Supercell  03/17/2023    61.0   

                                           genre  \
0                                  Drama, Action   
1             Science Fiction, Adventure, Action   
2  Animation, Adventure, Family, Fantasy, Comedy   
3  Animation, Comedy, Family, Adventure, Fantasy   
4                                         Action   

                                            overview  \
0  After dominating the boxing world, Adonis Cree...   
1  Set more than a decade after the events of the...   
2  While working underground to fix a water main,...   
3  Through a series of unfortunate events, three ...   
4  Good-hearted teenager William always lived in ...   

                                                crew  \
0  Michael B. Jordan, Adonis Creed, Tessa Thompso...   
1  Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...   
2  Chris Pratt, Mario (voice), Anya Taylor-Joy, P...   
3  Óscar Barberán, Thut (voice), Ana Esther Albor...   
4  Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...   

                    orig_title     status            orig_lang     budget_x  \
0                    Creed III   Released              English   75000000.0   
1     Avatar: The Way of Water   Released              English  460000000.0   
2  The Super Mario Bros. Movie   Released              English  100000000.0   
3                       Momias   Released   Spanish, Castilian   12300000.0   
4                    Supercell   Released              English   77000000.0   

        revenue country  
0  2.716167e+08      AU  
1  2.316795e+09      AU  
2  7.244590e+08      AU  
3  3.420000e+07      AU  
4  3.409420e+08      US

In [8]:
dataset.shape

(10178, 12)

In [9]:
index = [i for i in range(len(dataset['names']))]
index
dataset['index'] = index
dataset

names       date_x  score  \
0                                    Creed III  03/02/2023    73.0   
1                     Avatar: The Way of Water  12/15/2022    78.0   
2                  The Super Mario Bros. Movie  04/05/2023    76.0   
3                                      Mummies  01/05/2023    70.0   
4                                    Supercell  03/17/2023    61.0   
...                                        ...          ...    ...   
10173                       20th Century Women  12/28/2016    73.0   
10174  Delta Force 2: The Colombian Connection  08/24/1990    54.0   
10175                         The Russia House  12/21/1990    61.0   
10176         Darkman II: The Return of Durant  07/11/1995    55.0   
10177       The Swan Princess: A Royal Wedding  07/20/2020    70.0   

                                                   genre  \
0                                          Drama, Action   
1                     Science Fiction, Adventure, Action   
2          Animation, Adventure, Family, Fantasy, Comedy   
3          Animation, Comedy, Family, Adventure, Fantasy   
4                                                 Action   
...                                                  ...   
10173                                              Drama   
10174                                             Action   
10175                           Drama, Thriller, Romance   
10176  Action, Adventure, Science Fiction, Thriller, ...   
10177                         Animation, Family, Fantasy   

                                                overview  \
0      After dominating the boxing world, Adonis Cree...   
1      Set more than a decade after the events of the...   
2      While working underground to fix a water main,...   
3      Through a series of unfortunate events, three ...   
4      Good-hearted teenager William always lived in ...   
...                                                  ...   
10173  In 1979 Santa Barbara, California, Dorothea Fi...   
10174  When DEA agents are taken captive by a ruthles...   
10175  Barley Scott Blair, a Lisbon-based editor of R...   
10176  Darkman and Durant return and they hate each o...   
10177  Princess Odette and Prince Derek are going to ...   

                                                    crew  \
0      Michael B. Jordan, Adonis Creed, Tessa Thompso...   
1      Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...   
2      Chris Pratt, Mario (voice), Anya Taylor-Joy, P...   
3      Óscar Barberán, Thut (voice), Ana Esther Albor...   
4      Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...   
...                                                  ...   
10173  Annette Bening, Dorothea Fields, Lucas Jade Zu...   
10174  Chuck Norris, Col. Scott McCoy, Billy Drago, R...   
10175  Sean Connery, Bartholomew 'Barley' Scott Blair...   
10176  Larry Drake, Robert G. Durant, Arnold Vosloo, ...   
10177  Nina Herzog, Princess Odette (voice), Yuri Low...   

                                    orig_title     status  \
0                                    Creed III   Released   
1                     Avatar: The Way of Water   Released   
2                  The Super Mario Bros. Movie   Released   
3                                       Momias   Released   
4                                    Supercell   Released   
...                                        ...        ...   
10173                       20th Century Women   Released   
10174  Delta Force 2: The Colombian Connection   Released   
10175                         The Russia House   Released   
10176         Darkman II: The Return of Durant   Released   
10177       The Swan Princess: A Royal Wedding   Released   

                 orig_lang     budget_x       revenue country  index  
0                  English   75000000.0  2.716167e+08      AU      0  
1                  English  460000000.0  2.316795e+09      AU      1  
2                  English  100000000.0  7.244590e+08      AU      2  
3       Spanish, Cas

In [10]:
features = ['genre' ,'overview' , 'crew' ]
print(features)

['genre', 'overview', 'crew']


In [11]:
for f in features:
  dataset[f]=dataset[f].fillna('')

In [12]:
combined_data = dataset['genre']+' '+ dataset['overview']+' '+dataset['crew']

In [13]:
combined_data

0        Drama, Action After dominating the boxing worl...
1        Science Fiction, Adventure, Action Set more th...
2        Animation, Adventure, Family, Fantasy, Comedy ...
3        Animation, Comedy, Family, Adventure, Fantasy ...
4        Action Good-hearted teenager William always li...
                               ...                        
10173    Drama In 1979 Santa Barbara, California, Dorot...
10174    Action When DEA agents are taken captive by a ...
10175    Drama, Thriller, Romance Barley Scott Blair, a...
10176    Action, Adventure, Science Fiction, Thriller, ...
10177    Animation, Family, Fantasy Princess Odette and...
Length: 10178, dtype: object

In [14]:
vectrozer = TfidfVectorizer()

In [15]:
feature_verctrozer = vectrozer.fit_transform(combined_data)

In [16]:
print(feature_verctrozer)

  (0, 17635)	0.02684008523955383
  (0, 857)	0.030987693199648336
  (0, 1208)	0.0755241267248704
  (0, 17220)	0.11236936580345763
  (0, 62647)	0.07863725343588886
  (0, 8110)	0.19019650105873684
  (0, 68610)	0.04293036773316088
  (0, 1052)	0.35988606141901197
  (0, 13946)	0.39822107624856323
  (0, 26731)	0.07900517375592679
  (0, 5925)	0.05540875701977621
  (0, 62890)	0.11693449343857998
  (0, 29561)	0.06375163747431808
  (0, 7957)	0.06311837465987914
  (0, 27922)	0.07780503975834184
  (0, 10120)	0.07115505268901962
  (0, 2547)	0.03601923045643127
  (0, 20642)	0.03451898543653006
  (0, 36710)	0.040927070950324294
  (0, 67870)	0.03156784651787811
  (0, 11521)	0.07211769892069553
  (0, 22538)	0.05469973360669082
  (0, 22122)	0.12294946726721247
  (0, 49822)	0.10397047671264419
  (0, 14731)	0.2792536326496664
  :	:
  (10177, 44759)	0.10112973240770622
  (10177, 40732)	0.11319722398152625
  (10177, 11338)	0.38435879103188625
  (10177, 31775)	0.08465176060936853
  (10177, 57786)	0.1087945983

In [17]:
similar = cosine_similarity(feature_verctrozer)

In [18]:
print(similar)

[[1.         0.03912284 0.02090619 ... 0.01812748 0.01546524 0.01217461]
 [0.03912284 1.         0.01217543 ... 0.02805997 0.04447587 0.01631525]
 [0.02090619 0.01217543 1.         ... 0.01931088 0.01260347 0.11627437]
 ...
 [0.01812748 0.02805997 0.01931088 ... 1.         0.01152093 0.00184563]
 [0.01546524 0.04447587 0.01260347 ... 0.01152093 1.         0.01841989]
 [0.01217461 0.01631525 0.11627437 ... 0.00184563 0.01841989 1.        ]]


In [19]:
movie_name = input()

In [20]:
names = dataset['names'].tolist()
print(names)

['Creed III', 'Avatar: The Way of Water', 'The Super Mario Bros. Movie', 'Mummies', 'Supercell', 'Cocaine Bear', 'John Wick: Chapter 4', 'Puss in Boots: The Last Wish', 'Attack on Titan', 'The Park', 'Winnie the Pooh: Blood and Honey', 'The Exorcist', 'Murder Mystery 2', 'Black Panther: Wakanda Forever', "The Pope's Exorcist", 'Prizefighter: The Life of Jem Belcher', 'Knock at the Cabin', 'The Devil Conspiracy', 'Cazadora', 'Gold Run', "The Magician's Elephant", 'Plane', 'The Passion of the Christ', 'Batman: The Doom That Came to Gotham', 'Shazam! Fury of the Gods', 'Consecration', 'Shark Side of the Moon', 'Black Adam', 'Money Shot: The Pornhub Story', 'M3GAN', 'Ant-Man and the Wasp: Quantumania', 'Sayen', 'Die Hart', '13 Exorcisms', "H.P. Lovecraft's Witch House", 'John Wick: Chapter 2', 'Sick', 'Black Warrant', 'Shotgun Wedding', 'John Wick: Chapter 3 - Parabellum', 'Legion of Super-Heroes', 'Fall', 'Lord of the Streets', 'Little Dixie', 'The Whale', 'Prey for the Devil', 'Bandit', 

In [21]:
close_name = difflib.get_close_matches(movie_name , names )
print(close_name)

['Fatman', 'Catman', 'Batman']


In [22]:
close_match = close_name[0]
close_match

'Fatman'

In [23]:
index_of_the_movie = dataset[dataset.names == close_match]['index'].values[0]
index_of_the_movie

8525

In [24]:
similar_score = list(enumerate(similar[index_of_the_movie]))
print(similar_score)

[(0, 0.027441267193196704), (1, 0.009280660956622633), (2, 0.018900009297568625), (3, 0.013034855371966695), (4, 0.028074999492213426), (5, 0.007369263319660972), (6, 0.013532745724904356), (7, 0.014553140753973385), (8, 0.00690032236803133), (9, 0.019677237983221494), (10, 0.019890112914043242), (11, 0.01356577649963376), (12, 0.012685449855411101), (13, 0.0073221389815905265), (14, 0.006951804000258155), (15, 0.007694463172019973), (16, 0.007889592220280331), (17, 0.012478048544938261), (18, 0.006570340509800751), (19, 0.0054865162656055405), (20, 0.030209506036417172), (21, 0.02337488298528506), (22, 0.0023603712332346), (23, 0.008661764088978029), (24, 0.038960494267463744), (25, 0.017466340391848717), (26, 0.02237437874592857), (27, 0.015042131372173504), (28, 0.001670824493943414), (29, 0.004443507963501783), (30, 0.011270101914845754), (31, 0.007510226967401907), (32, 0.01716737708717919), (33, 0.01996782248563525), (34, 0.012736699041069924), (35, 0.008720435053562622), (36, 0.

In [25]:
len(similar_score)

10178

In [26]:
sorted_similar = sorted(similar_score , key = lambda x:x[1] , reverse= True)
sorted_similar

[(8525, 1.0),
 (7323, 0.16260078547681794),
 (9777, 0.13993290953428922),
 (3476, 0.1239888261552606),
 (9690, 0.11899205280239245),
 (9132, 0.11792914702125502),
 (6794, 0.11157848121056),
 (3784, 0.10229423620608039),
 (7165, 0.09542641330842087),
 (4927, 0.09145862146378284),
 (5886, 0.09107453810706767),
 (7477, 0.09050704172834179),
 (6353, 0.09048738287257142),
 (7261, 0.09046096339595669),
 (4597, 0.09033258668337173),
 (94, 0.08975467431196342),
 (4678, 0.08868361613617395),
 (872, 0.08704150323814938),
 (7345, 0.08663857239245269),
 (2804, 0.08605724209397242),
 (6623, 0.0842611854838191),
 (42, 0.08209679135586462),
 (3748, 0.08205758974459079),
 (8368, 0.07874753270259602),
 (1935, 0.07756761042737223),
 (9010, 0.0772805039581659),
 (1713, 0.07693771160562682),
 (9627, 0.07542590118608426),
 (5017, 0.0754085147161146),
 (5967, 0.07464796946465531),
 (4645, 0.07166521443927935),
 (7896, 0.07120102603238695),
 (6798, 0.07072319719984169),
 (8124, 0.07068236232092957),
 (606, 0

In [27]:
i=1
for movie  in sorted_similar :
  index = movie[0]
  title=dataset[dataset.index==index]['names'].values[0]
  if(i<30):
    print(' ',title)
    i+=1

  Fatman
  Fred Claus
  The Search for Santa Paws
  The Christmas Chronicles: Part Two
  Miracle on 34th Street
  It's a SpongeBob Christmas!
  The Christmas Chronicles
  Teen Titans Go! vs. Teen Titans
  Miracle on 34th Street
  Arthur Christmas
  Elf
  Heart Shot
  Mickey's Twice Upon a Christmas
  The Santa Clause
  Billy Madison
  Violent Night
  David and the Elves
  The Nightmare Before Christmas
  Rudolph the Red-Nosed Reindeer
  The Hateful Eight
  Merry Madagascar
  Lord of the Streets
  I Believe in Santa
  Santa vs Reyes
  Sinister
  U Turn
  What Dreams May Come
  The Santa Clause 3: The Escape Clause
  Ice Age: A Mammoth Christmas


In [29]:
import pandas as pd
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load your dataset
dataset = pd.read_csv('imdb_movies.csv')

# Fill missing values
features = ['genre', 'overview', 'crew']
for f in features:
    dataset[f] = dataset[f].fillna('')

# Combine features
combined_features = dataset['genre'] + ' ' + dataset['overview'] + ' ' + dataset['crew']

# Vectorize
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)

# Compute cosine similarity matrix
similarity = cosine_similarity(feature_vectors)

# Add index column (used in recommendation)
dataset['index'] = range(len(dataset))

# Save files
joblib.dump(dataset, 'movies_data.pkl')
joblib.dump(similarity, 'recommender_model.pkl')

print("Saved movies_data.pkl and recommender_model.pkl successfully!")

Saved movies_data.pkl and recommender_model.pkl successfully!


In [30]:
import joblib

dataset = joblib.load('movies_data.pkl')
similarity = joblib.load('recommender_model.pkl')

print(dataset.head())
print(similarity.shape)

                         names       date_x  score  \
0                    Creed III  03/02/2023    73.0   
1     Avatar: The Way of Water  12/15/2022    78.0   
2  The Super Mario Bros. Movie  04/05/2023    76.0   
3                      Mummies  01/05/2023    70.0   
4                    Supercell  03/17/2023    61.0   

                                           genre  \
0                                  Drama, Action   
1             Science Fiction, Adventure, Action   
2  Animation, Adventure, Family, Fantasy, Comedy   
3  Animation, Comedy, Family, Adventure, Fantasy   
4                                         Action   

                                            overview  \
0  After dominating the boxing world, Adonis Cree...   
1  Set more than a decade after the events of the...   
2  While working underground to fix a water main,...   
3  Through a series of unfortunate events, three ...   
4  Good-hearted teenager William always lived in ...   

                         